a = int(input("Введите целое число"))
b = int(input("Введите целое число"))
print(f"{a + b}")
print(f"{a - b}")
print(f"{a * b}")
print(f"{a / b}")
print(f"{a // b}")
print(f"{a % b}")
print(f"{a ** b}")
print(f"{a == b}")
print(f"{a < b}")
print(f"{a > b}")
print(f"{a <= b}")
print(f"{a >= b}")
print(f"{a != b}")